application: emojitalianobot
version: 6
runtime: python27
api_version: 1
threadsafe: false

#inbound_services:
#- channel_presence

# Fx: auto scaling
# Bx: manual or basic scaling
# instance_class: B4
# basic_scaling:
#   max_instances: 2
#   idle_timeout: 5m

builtins:
- remote_api: on
- deferred: on

# env_variables:
#     GAE_USE_SOCKETS_HTTPLIB : 'true'

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /set_webhook
  login: admin
  script: main.app

- url: /get_webhook_info
  login: admin
  script: main.app

- url: /delete_webhook
  login: admin
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

#- url: /_ah/channel/connected/
#  script: com.pickmeup-telegram.server.channel.ChannelConnected
#  name: ChannelConnected
#  script: main.app

#- url: /_ah/channel/disconnected/
#  script: com.pickmeup-telegram.server.channel.ChannelDisconnected
#  name: ChannelDisconnected
#  script: main.app

- url: .*
  script: main.app

- url: /EmojiData
  static_dir: emojiLanguages
  application_readable: true


libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest

skip_files:
  - ^Makefile$
  - env/
  # Defaults
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$